# Generated by Django 5.1.7 on 2025-03-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='client_type',
            field=models.CharField(blank=True, choices=[('KVO', 'KVO'), ('Personal', 'Personal'), ('Other', 'Other')], max_length=10),
        ),
    ]
